### ISSUE TITLE
Broken workshop link

### ISSUE THREAD

**Issue by Michae1CC** [jennapederson/hello-flask#1]
Has the link for the workshop moved? www.eventbox.dev seems down.

**Comment by jennapederson** [comment]
@Michae1CC Hey Michael - Thanks for flagging this! That workshop platform has since been decomissioned and it looks like I missed cleaning up this link. However, you can find a blog post covering the same solution here: https://www.jennapederson.com/blog/automate-your-container-deployments-with-ci-cd-and-github-actions/

**Comment by Michae1CC** [comment]
Perfect, thank you @jennapederson !
